administrator/urls.py
from django.urls import path
from .views import *

app_name = 'administrator'

urlpatterns = [
    path('login/', Login, name='login'),
    path('logout/', Logout, name='logout'),
    path('signup/', Register, name='signup'),
    path('post/', create_post, name="create_post"),
    path('profile/', profile_view, name='profile'),
    path('profile_edit/', profile_save, name='profile_save'),
    path('shoping_cart/', shping_cart, name='shping_cart'),
    path('buy/<int:id>/', Buy, name="buy"),
    path('delete/<int:id>/', delete, name="delete"),
    path('credit_cart/', credit_cart, name="credit_cart"),
]

bread_new/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('administrator.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

administrator/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)

# Create your models here.


class UserManager(BaseUserManager):
    def create_user(self, email, username, password):
        if not email:
            raise ValueError('please enter an email')

        if not username:
            raise ValueError('please enter an username')

        user = self.model(email=self.normalize_email(email), username=username)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password):
       user = self.create_user(email, username, password)
       user.is_admin = True
       user.save(using=self._db)
       return user


class User(AbstractBaseUser):
    username = models.CharField(max_length=50)
    email = models.EmailField(unique=True)
    user_id = models.AutoField(primary_key=True, auto_created=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']
    objects = UserManager()

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin


class profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.IntegerField(null=True)
    city = models.CharField(max_length=200)
    address = models.TextField()
    verify_phone = models.BooleanField(default=False)


def save_profile_user(sender, **kwargs):
    if kwargs['created']:
        profile_user = profile(user=kwargs['instance'])
        profile_user.save()


post_save.connect(save_profile_user, sender=User)


class post(models.Model):
    # user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="post")
    title = models.CharField(max_length=100)
    description = models.TextField()
    count = models.IntegerField()
    price = models.DecimalField(max_digits=6, decimal_places=0)
    active = models.BooleanField(default=True)
    image = models.ImageField(upload_to='images')
    def __str__(self):
        return self.title


class buy(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="buy")
    post = models.ForeignKey(post, on_delete=models.CASCADE, related_name="post")
    bread_count = models.IntegerField()
    Total_price = models.IntegerField()
    arrived = models.BooleanField(default=False)
    send = models.BooleanField(default=False)
    discount = models.TextField(null=True, blank=True)

administrator/forms.py
from django import forms
from .models import User, profile, buy
from django.contrib.auth.forms import ReadOnlyPasswordHashField


class UserCreateForm(forms.ModelForm):
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['email', 'username']

    def clean_password2(self):
        data = self.cleaned_data
        if data['password2'] and data['password1'] and data['password2'] != data['password1']:
            raise forms.ValidationError('PLEASE CHECK THE PASSWORD')
        return data['password2']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password2'])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField

    class Meta:
        model = User
        fields = ['email', 'username']

    def clean_password(self):
        return self.initial['password']


class UserProfileUpdate(forms.ModelForm):
    class Meta:
        model = profile
        fields = ['first_name', 'last_name', 'phone', 'city', 'address']


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model=User
        fields = ['email', 'username']


class buy_form(forms.ModelForm):
    class Meta:
        model=buy
        fields = ['bread_count', 'discount']

administrator/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.contrib.auth import authenticate, login,logout
from .forms import *
from django.contrib.auth.models import User
from .models import *
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required


def Register(request):
    if request.user.is_authenticated:
        return redirect('administrator:create_post')
    if request.method == 'POST':
        form = UserCreateForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = User.objects.create_user(username=data['username'], email=data['email'], password=data['password2'])
            user.save()
            return redirect('administrator:login')
    else:
        form = UserCreateForm()
    context = {'form': form}
    return render(request, 'administrator/signup_and _login.html', context)


def Login(request):
    if request.user.is_authenticated:
        return redirect('administrator:create_post')
    if request.method == 'POST':
        username = request.POST.get('email')
        password = request.POST.get('password')
        print(username)
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect("administrator:create_post")
        else:

            return render(request,  'administrator/login.html')
    else:
        return render(request,  'administrator/login.html', {})


@login_required(login_url='/administrator/login/')
def Logout(request):
    logout(request)
    return redirect('administrator:login')


@login_required(login_url='/administrator/login/')
def profile_view(request):
    context = {
        'profile': profile.objects.get(user_id=request.user.user_id),

    }
    return render(request, 'administrator/profile.html', context)


@login_required(login_url='/administrator/login/')
def profile_save(request):
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        user_profile = UserProfileUpdate(request.POST, instance=request.user.profile)

        if user_profile.is_valid() or user_form.is_valid():
            user_form.save()
            user_profile.save()
            # messages.success(request, 'Your profile is updated successfully')
            return redirect('administrator:profile')

    else:
        user_form = UserUpdateForm(instance=request.user)
        user_profile = UserProfileUpdate(instance=request.user.profile)
    context = {
        'user_form': user_form,
        'user_profile': user_profile,
    }
    return render(request, 'administrator/edit_profile.html', context)




@login_required(login_url='/administrator/login/')
def create_post(requests):
    context = {
        "post": post.objects.all(),
    }
    return render(requests, "administrator/product.html", context)


def Buy(request, id):
    if request.method == 'POST':
        buys = buy_form(request.POST)
        if buys.is_valid():
            data = buys.cleaned_data
            print(data)
            price = get_object_or_404(post, id=id).price
            total_price = price*data['bread_count']
            buy.objects.create(user_id=request.user.user_id, bread_count=data['bread_count'], Total_price=total_price, discount=data['discount'], post_id=id)
            posts =post.objects.get(id=id)
            posts.count = posts.count - data['bread_count']
            posts.save()
            return redirect('administrator:shping_cart')
    else:
        context = {
            "post": post.objects.get(id=id),
        }
        return render(request,  'administrator/shoping_cart.html', context)


@login_required(login_url='/administrator/login/')
def shping_cart(request):
    context = {
        'post': buy.objects.filter(user_id=request.user.user_id).order_by("-id")
    }
    return render(request, "administrator/shoping_cart_templates.html", context)


@login_required(login_url='/administrator/login/')
def delete(request, id):
    url = request.META.get('HTTP_REFERER')

    buy.objects.filter(id=id).delete()

    return redirect(url)

@login_required(login_url='/administrator/login/')
def credit_cart(request):

    return render(request, "administrator/credit_cart.html")

administrator/templates/administrator/credit_cart.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'administrator/credit_cart/css.css' %}">
    <title>Title</title>
</head>
<body>

<div class="card">
  <div class="card__front card__part">
    <img class="card__front-square card__square" src="https://image.ibb.co/cZeFjx/little_square.png">
    <img class="card__front-logo card__logo" src="https://www.fireeye.com/partners/strategic-technology-partners/visa-fireeye-cyber-watch-program/_jcr_content/content-par/grid_20_80_full/grid-20-left/image.img.png/1505254557388.png">
    <p class="card_numer">6037 5047 6291 6258</p>
    <div class="card__space-75">
      <span class="card__label">Card hold</span>
      <p class="card__info">Mohammad Taghdir</p>
    </div>
    <div class="card__space-25">
      <span class="card__label">Expires</span>
            <p class="card__info">10/25</p>
    </div>
  </div>

</div>
</body>
</html>

administrator/templates/administrator/edit_profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'administrator/edit_profile/css/edit_profile.css' %}">
    <title>profile</title>
</head>
<body>
    <div class="container rounded bg-white mt-5">
        <div class="row">
            <div class="col-md-12 border">
                <form method="POST" class="p-3 py-5">
                    {% csrf_token %}
                    <div class="d-flex justify-content-between align-items-center mb-3">
                        <div class="d-flex flex-row align-items-center back"><i style="color: #EAA636FF" class="fa fa-long-arrow-left mr-1 mb-1 "></i>
                            <a class="nav__link" style="color: #EAA636FF" href="{% url 'administrator:profile' %}"><h6>Back to home</h6></a>
                        </div>
                        <h6 class="text-right">Edit Profile</h6>
                    </div>
                    <div class="row mt-2">
                        <div class="col-md-6"><input type="text" name="first_name" class="form-control" placeholder="نام" value=""></div>
                        <div class="col-md-6"><input type="text" name="last_name" class="form-control" value="" placeholder="نام خانوادگی"></div>
                    </div>
                    <div class="row mt-3">
                        <div class="col-md-6"><input type="text" name="email" class="form-control" placeholder="ایمیل" value=""></div>
                        <div class="col-md-6"><input type="text" name="username" class="form-control" value="" placeholder="نام کاربری"></div>
                    </div>
                    <div class="row mt-3">
                        <div class="col-md-6"><input type="text" name="city" class="form-control" placeholder="شهر" value=""></div>
                        <div class="col-md-6"><input type="text" name="address" class="form-control" value="" placeholder="آدرس"></div>
                    </div>
                    <div class="row mt-3">
                        <div class="col-md-6"><input type="text" name="phone" class="form-control" placeholder="شماره تلفن" value=""></div>

                    </div>
                    <div class="mt-5 text-right"><button class="btn btn-primary profile-button" type="submit">Save Profile</button></div>
                </form>
            </div>

        </div>
    </div>
</body>
</html>

administrator/templates/administrator/header.html
{% load static %}
<!DOCTYPE html>
<head>
        <link href="{% static "administrator/css/nav.css" %}" rel="stylesheet">
</head>
<html lang="en">

<header class="header" id="header">
        <nav class="nav container">

                <div class="nav__menu" id="nav-menu">
                    <ul class="nav__list">
                        <li class="nav__item">
                            <a href="{% url 'administrator:create_post' %}" class="nav__link ">
                                <i class='bx bx-home-alt nav__icon'></i>
                                <span class="nav__name">Home</span>
                            </a>
                        </li>
                        <li class="nav__item">
                            <a href="{% url 'administrator:profile' %}" class="nav__link">
                                <i class='bx bx-book-alt nav__icon'></i>
                                <span class="nav__name">پروفایل</span>
                            </a>
                        </li>
                        <li class="nav__item">
                            <a href="{% url 'administrator:shping_cart' %}" class="nav__link ">
                                <i class='bx bx-home-alt nav__icon'></i>
                                <span class="nav__name">سبد خرید</span>
                            </a>
                        </li>

                    </ul>
                </div>


            </nav>
    </header>

</html>

administrator/templates/administrator/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login V2</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static "administrator/login/css/util.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "administrator/login/css/main.css" %}">
<!--===============================================================================================-->
</head>
<body>

	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<form class="login100-form validate-form" method="POST" >
                    {% csrf_token %}
					<span class="login100-form-title p-b-26">
						Welcome
					</span>
					<span class="login100-form-title p-b-48">
						<i class="zmdi zmdi-font"></i>
					</span>

					<div class="wrap-input100 validate-input" >
						<input class="input100" type="email" name="email">
						<span class="focus-input100" data-placeholder="Email"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Enter password">
						<span class="btn-show-pass">
							<i class="zmdi zmdi-eye"></i>
						</span>
						<input class="input100" type="password" name="password">
						<span class="focus-input100" data-placeholder="Password"></span>
					</div>

					<div class="container-login100-form-btn">
						<div class="wrap-login100-form-btn">
							<div class="login100-form-bgbtn"></div>
							<button class="login100-form-btn">
								Login
							</button>
						</div>
					</div>

					<div class="text-center p-t-115">
						<span class="txt1">
							Don’t have an account?
						</span>

						<a class="txt2" href="{% url 'administrator:signup' %}">
							Sign Up
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>


	<div id="dropDownSelect1"></div>

<!--===============================================================================================-->
	<script src="{% static "administrator/login/vendor/jquery/jquery-3.2.1.min.js" %}"></script>
<!--===============================================================================================-->
	<script src="{% static "administrator/login/vendor/animsition/js/animsition.min.js" %}"></script>
<!--===============================================================================================-->
	<script src="{% static "administrator/login/vendor/bootstrap/js/popper.js" %}"></script>
	<script src="{% static "administrator/login/vendor/bootstrap/js/bootstrap.min.js" %}"></script>
<!--===============================================================================================-->
	<script src="{% static "administrator/login/vendor/select2/select2.min.js" %}"></script>
<!--===============================================================================================-->
	<script src="{% static "administrator/login/vendor/daterangepicker/moment.min.js" %}"></script>
	<script src="{% static "administrator/login/vendor/daterangepicker/daterangepicker.js" %}"></script>
<!--===============================================================================================-->
	<script src="{% static "administrator/login/vendor/countdowntime/countdowntime.js" %}"></script>
<!--===============================================================================================-->
	<script src="{% static "administrator/login/js/main.js" %}"></script>

</body>
</html>

administrator/templates/administrator/product.html
{% load static %}
<html lang="en"><head>

  <meta charset="UTF-8">

<link rel="apple-touch-icon" type="image/png" href="https://cpwebassets.codepen.io/assets/favicon/apple-touch-icon-5ae1a0698dcc2402e9712f7d01ed509a57814f994c660df9f7a952f3060705ee.png">
<meta name="apple-mobile-web-app-title" content="CodePen">

<link rel="shortcut icon" type="image/x-icon" href="https://cpwebassets.codepen.io/assets/favicon/favicon-aec34940fbc1a6e787974dcd360f2c6b63348d4b1f4e06c77743096d55480f33.ico">

<link rel="mask-icon" type="image/x-icon" href="https://cpwebassets.codepen.io/assets/favicon/logo-pin-8f3771b1072e3c38bd662872f6b673a722f4b3ca2421637d5596661b4e2132cc.svg" color="#111">



  <title>CodePen - Shopping cart JS</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>



    <!-- Libraries Stylesheet -->
    <link href="{% static "administrator/lib/animate/animate.min.css" %}" rel="stylesheet">
    <link href="{% static "administrator/lib/owlcarousel/assets/owl.carousel.min.css" %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static "administrator/css/bootstrap.min.css" %}" rel="stylesheet">

<link href="{% static "administrator/css/style.css" %}" rel="stylesheet">


</head>

<body translate="no">


<!-- Main -->
    <div class=" bg-light my-6 py-6 pt-0">
        <div class="container">
            <div class="row g-4">
                {% for posts in post %}
                    <div class="col-lg-4 col-md-6 wow fadeInUp" >
                        <div class="product-item d-flex flex-column bg-white rounded overflow-hidden h-100">

                                <div class="position-relative mt-auto">
                                <img class="img-fluid" src="{{ posts.image.url }}" alt="">

                                </div>
                                <div class=" p-5">


                                    <div style="display: flex; justify-content: space-between">
                                        <h3 class="mb-3">{{ posts.title }}</h3>
                                        <div>

                                            <div class="d-inline-block " STYLE="margin-right: 10px">{{ posts.price }}</div>
                                        </div>
                                    </div>
                                    <div style="display: flex; justify-content: space-between">
                                        <span>{{ posts.description }}</span>
                                        <a href="{% url 'administrator:buy' posts.id %}" data-name="{{ posts.title }}" data-price="{{ posts.price }}" class="add-to-cart border border-primary   btn  btn-outline-primary ">Add to cart</a>

                                </div>

                                </div>


                        </div>
                    </div>
                {% endfor %}
            </div>

        </div>
    </div>


 <!-- Modal -->
<div class="modal fade" id="cart" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Cart</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">
        <table class="show-cart table"></table>
        <div>Total price: $<span class="total-cart">0</span></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Order now</button>
      </div>
    </div>
  </div>
</div>










</body></html>

administrator/templates/administrator/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.bundle.min.js">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js">
    <link rel="stylesheet" href="{% static 'administrator/profile/css/profile.css' %}">
    <title>profile</title>
</head>

<body>
    {% include 'administrator/header.html' %}

    <div class="row py-5 my-6 py-6 px-4" style="margin-top: 3rem">
        <div class="col-md-5 mx-auto">
            <!-- Profile widget -->
            <div class="bg-white shadow rounded overflow-hidden">
                <div class="px-4 pt-0 pb-4 cover">
                    <div class="media align-items-end profile-head">
                        <div class="profile mr-3">
                            <img src="{% static 'administrator/img/pic-5.png' %}" alt="..." width="130" class="rounded mb-2 img-thumbnail">
                                <a href="{% url 'administrator:profile_save' %}" class="hh btn btn-outline-dark btn-sm btn-block">Edit profile</a></div>
                        <div class="media-body mb-5 ">
                            <h4 class="mt-0 mb-0">{{ profile.first_name }}</h4>
                            <p class="small mb-4"> <i class="fas fa-map-marker-alt mr-2"></i>{{ profile.city }}</p>
                        </div>
                    </div>
                </div>
                <div class="bg-light p-4 d-flex justify-content-end text-center">
                    <h4 class="mt-0 mr-2 mb-0">{{ profile.phone }}</h4>

                </div>
                <div class="px-4 py-3">
                    <div class="back p-4 rounded shadow-sm  ">
                        <p class="font-italic mb-0">{{ profile.address }}</p>
                    </div>
                </div>
{#                <div class="py-4 px-4">#}
{#                    <div class="d-flex align-items-center justify-content-between mb-3">#}
{#                        <h5 class="mb-0">سفارشات اخیر</h5>#}
{#                    </div>#}
{#                    <div class="row">#}
{#                        {% for posts in post %}#}
{#                            <div class="col-lg-6 mb-5 pr-lg-1  "><a href="{% url 'administrator:buy' posts.post.id %}"><img#}
{#                                src="{{ posts.post.image.url }}"#}
{#                                alt="" class="img-fluid rounded shadow-sm"></a>#}
{#                                <h4 class="mt-0 mb-0">{{ posts.post.title}}</h4>#}
{##}
{#                            </div>#}
{##}
{#                        {% endfor %}#}
{##}
{##}
{#                    </div>#}
{#                </div>#}
            </div>
        </div>
    </div>
</body>

</html>

administrator/templates/administrator/shoping_cart_templates.html
{% load static %}
<html lang="en"><head>

  <meta charset="UTF-8">

<link rel="apple-touch-icon" type="image/png" href="https://cpwebassets.codepen.io/assets/favicon/apple-touch-icon-5ae1a0698dcc2402e9712f7d01ed509a57814f994c660df9f7a952f3060705ee.png">
<meta name="apple-mobile-web-app-title" content="CodePen">

<link rel="shortcut icon" type="image/x-icon" href="https://cpwebassets.codepen.io/assets/favicon/favicon-aec34940fbc1a6e787974dcd360f2c6b63348d4b1f4e06c77743096d55480f33.ico">

<link rel="mask-icon" type="image/x-icon" href="https://cpwebassets.codepen.io/assets/favicon/logo-pin-8f3771b1072e3c38bd662872f6b673a722f4b3ca2421637d5596661b4e2132cc.svg" color="#111">



  <title>CodePen - Shopping cart JS</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>



    <!-- Libraries Stylesheet -->
    <link href="{% static "administrator/lib/animate/animate.min.css" %}" rel="stylesheet">
    <link href="{% static "administrator/lib/owlcarousel/assets/owl.carousel.min.css" %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static "administrator/css/bootstrap.min.css" %}" rel="stylesheet">

    <link href="{% static "administrator/css/style.css" %}" rel="stylesheet">



</head>

<body translate="no">
    {% include 'administrator/header.html' %}

<!-- Main -->
    <div class="  bg-light my-6 py-6 pt-0">
        <div class="container">
            <div class="row g-4">
                {% for posts in post %}
                    <div class="col-lg-4 col-md-6 wow fadeInUp" >
                        <div class="product-item d-flex flex-column bg-white rounded overflow-hidden h-100">

                                <div class="position-relative mt-auto">

                                <img class="img-fluid" src="{{ posts.post.image.url }}" alt="">

                                </div>
                                <div class=" p-5">


                                    <div style="display: flex; justify-content: space-between">
                                        <h3 class="mb-3">{{ posts.post.title }}</h3>
                                        <div>

                                            <div class="d-inline-block " STYLE="margin-right: 10px">{{ posts.bread_count }} -  {{ posts.Total_price }}</div>
                                        </div>
                                    </div>
                                    <div style="display: flex; justify-content: space-between">
                                        <span>{{ posts.post.description }}</span>
                                        <a href="{% url 'administrator:credit_cart' %}"  class="add-to-cart border border-primary   btn  btn-outline-primary ">تکمیل خرید</a>

                                </div>
                                    <div style="display: flex; justify-content: end; margin-top: 10px">
                                        <a style="border-radius: 200px" href="{% url 'administrator:delete' posts.id %}" class="delete border border-danger   btn  btn-outline-danger ">delete</a>

                                    </div>
                                </div>


                        </div>
                    </div>
                {% endfor %}
            </div>

        </div>
    </div>


</body></html>